create database Nhom10ModuleDiemDanh
GO
USE Nhom10ModuleDiemDanh;
GO
CREATE TABLE DiaDiem (
    IdDiaDiem UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TenDiaDiem NVARCHAR(100) NOT NULL,
    ViDo FLOAT NULL,
    KinhDo FLOAT NULL,
    BanKinh FLOAT NULL,
    NgayTao DATETIME NOT NULL DEFAULT GETDATE(),
    NgayCapNhat DATETIME NULL,
    TrangThai BIT NOT NULL DEFAULT 1
);

CREATE TABLE CaHoc (
    IdCaHoc UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    CaHoc NVARCHAR(50),
    ThoiGianBatDau TIME,
    ThoiGianKetThuc TIME,
    MoTa NVARCHAR(255),
    NgayCapNhat DATETIME DEFAULT GETDATE(),
    TrangThai INT DEFAULT 1
);
GO
CREATE TABLE CapDoDuAn (
    IdCDDA UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TenCapDoDuAn NVARCHAR(255) NOT NULL,
    MaCapDoDuAn NVARCHAR(50) NOT NULL,
    MoTa NVARCHAR(255) NULL,
    NgayTao DATETIME NOT NULL DEFAULT GETDATE(),
    NgayCapNhat DATETIME NULL,
    TrangThai int NOT NULL DEFAULT 1
);
GO
CREATE TABLE VaiTro (
    IdVaiTro UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TenVaiTro NVARCHAR(100) NOT NULL,
    NgayTao DATETIME NOT NULL DEFAULT GETDATE(),
    NgayCapNhat DATETIME NULL,
    TrangThai BIT NOT NULL DEFAULT 1
);
GO

-- Bảng IP
CREATE TABLE IP (
    IdIP UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    KieuIP NVARCHAR(50) NOT NULL,
    IP_DaiIP NVARCHAR(100) NOT NULL,
    NgayTao DATETIME NOT NULL DEFAULT GETDATE(),
    NgayCapNhat DATETIME NULL,
    TrangThai BIT NOT NULL DEFAULT 1
);

GO
CREATE TABLE QuanLyBoMon (
    IDBoMon UNIQUEIDENTIFIER PRIMARY KEY,
    MaBoMon NVARCHAR(50),
    TenBoMon NVARCHAR(100),
    CoSoHoatDong NVARCHAR(100),
    NgayTao DATETIME,
    NgayCapNhat DATETIME,
    TrangThai INT
);
GO
CREATE TABLE HocKy (
    IdHocKy UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TenHocKy NVARCHAR(100) NOT NULL,
    MaHocKy NVARCHAR(50) NOT NULL,
    NgayBatDau DATE NOT NULL,
    NgayKetThuc DATE NOT NULL,
    TrangThai BIT NOT NULL DEFAULT 1,
    NgayTao DATETIME NOT NULL DEFAULT GETDATE(),
    NgayCapNhat DATETIME NULL
);
go
CREATE TABLE CoSo (
    IdCoSo UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    MaCoSo NVARCHAR(50) NOT NULL,
    TenCoSo NVARCHAR(100) NOT NULL,
    TrangThai BIT NOT NULL,
    NgayTao DATETIME NOT NULL DEFAULT GETDATE(),
    NgayCapNhat DATETIME NULL,
    IdCaHoc UNIQUEIDENTIFIER,
    IdIP UNIQUEIDENTIFIER,
    IdDiaDiem UNIQUEIDENTIFIER,

    CONSTRAINT FK_CoSo_CaHoc FOREIGN KEY (IdCaHoc) REFERENCES CaHoc(IdCaHoc),
    CONSTRAINT FK_CoSo_IP FOREIGN KEY (IdIP) REFERENCES IP(IdIP),
    CONSTRAINT FK_CoSo_DiaDiem FOREIGN KEY (IdDiaDiem) REFERENCES DiaDiem(IdDiaDiem)
);

go

-- Tạo bảng BoMonCoSo
CREATE TABLE BoMonCoSo (
    IdBoMonCoSo UNIQUEIDENTIFIER PRIMARY KEY,
    IDBoMon UNIQUEIDENTIFIER,
    IdCoSo UNIQUEIDENTIFIER,
    TrangThai INT,

    FOREIGN KEY (IDBoMon) REFERENCES QuanLyBoMon(IDBoMon),
    FOREIGN KEY (IdCoSo) REFERENCES CoSo(IdCoSo)
);
GO

-- Tạo bảng BanDaoTao
CREATE TABLE BanDaoTao (
    IdBDT UNIQUEIDENTIFIER PRIMARY KEY,
    MaBanDaoTao NVARCHAR(50),
    TenBanDaoTao NVARCHAR(100),
    Email NVARCHAR(100),
    IdVaiTro UNIQUEIDENTIFIER,
    TrangThai INT,
    NgayTao DATETIME,
    NgayCapNhat DATETIME,
	CONSTRAINT FK_BanDaoTao_VaiTro FOREIGN KEY (IdVaiTro) REFERENCES VaiTro(IdVaiTro)
);
GO

CREATE TABLE DuAn (
    IdDuAn UNIQUEIDENTIFIER PRIMARY KEY,
    TenDuAn NVARCHAR(255) NOT NULL,
    IdCDDA UNIQUEIDENTIFIER,
    IdHocKy UNIQUEIDENTIFIER,
    IDBoMon UNIQUEIDENTIFIER,
    MoTa NVARCHAR(MAX),
    NgayTao DATETIME DEFAULT GETDATE(),
    NgayCapNhat DATETIME DEFAULT GETDATE(),
    TrangThai BIT,

    FOREIGN KEY (IdCDDA) REFERENCES CapDoDuAn(IdCDDA),
    FOREIGN KEY (IdHocKy) REFERENCES HocKy(IdHocKy),
    FOREIGN KEY (IDBoMon) REFERENCES QuanLyBoMon(IDBoMon)
);

GO
CREATE TABLE PhuTrachXuong (
    IdNhanVien UNIQUEIDENTIFIER PRIMARY KEY,
    TenNhanVien NVARCHAR(100) NOT NULL,
    MaNhanVien VARCHAR(50) NOT NULL,
    EmailFE VARCHAR(100),
    EmailFPT VARCHAR(100),
    IdCoSo UNIQUEIDENTIFIER NOT NULL,
    NgayTao DATETIME DEFAULT GETDATE(),
    NgayCapNhat DATETIME DEFAULT GETDATE(),
    TrangThai BIT DEFAULT 1,
    
    CONSTRAINT FK_PTX_CoSo FOREIGN KEY (IdCoSo) REFERENCES CoSo(IdCoSo),
);

GO
CREATE TABLE NhomXuong (
    IdNhomXuong UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TenNhomXuong NVARCHAR(100),
    IdDuAn UNIQUEIDENTIFIER,
    IdBoMon UNIQUEIDENTIFIER,
    IdNhanVien UNIQUEIDENTIFIER,
    MoTa NVARCHAR(255),
    NgayTao DATETIME DEFAULT GETDATE(),
    NgayCapNhat DATETIME NULL,
    TrangThai INT DEFAULT 1,

	CONSTRAINT FK_NhomXuong_DuAn FOREIGN KEY (IdDuAn) REFERENCES DuAn(IdDuAn),
	CONSTRAINT FK_NhomXuong_BoMon FOREIGN KEY (IdBoMon) REFERENCES QuanLyBoMon(IdBoMon),
	CONSTRAINT FK_NhomXuong_NhanVien FOREIGN KEY (IdNhanVien) REFERENCES PhuTrachXuong(IdNhanVien)
);
GO
CREATE TABLE LichHoc (
    IdLichHoc UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    IdNXCH UNIQUEIDENTIFIER NOT NULL,
    IdCaHoc UNIQUEIDENTIFIER NOT NULL,
    IdNhomXuong UNIQUEIDENTIFIER NOT NULL,
    IdDuAn UNIQUEIDENTIFIER NULL,
    DiaDiem NVARCHAR(100),
    TenGiangVien NVARCHAR(100),
    NgayTao DATETIME NOT NULL DEFAULT GETDATE(),
    NgayCapNhat DATETIME NULL,
    MoTa NVARCHAR(255),

    CONSTRAINT FK_LichHoc_NXCH FOREIGN KEY (IdNXCH) REFERENCES CoSo(IdCoSo),
    CONSTRAINT FK_LichHoc_CaHoc FOREIGN KEY (IdCaHoc) REFERENCES CaHoc(IdCaHoc),
    CONSTRAINT FK_LichHoc_NhomXuong FOREIGN KEY (IdNhomXuong) REFERENCES NhomXuong(IdNhomXuong),
    CONSTRAINT FK_LichHoc_DuAn FOREIGN KEY (IdDuAn) REFERENCES DuAn(IdDuAn)
);
GO

CREATE TABLE LichGiangDay (
    IdLichDay UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    IdNXCH UNIQUEIDENTIFIER NOT NULL,
    TTDiemDanhMuon BIT NOT NULL DEFAULT 0,
    IdNhomXuong UNIQUEIDENTIFIER NOT NULL,
    IdDuAn UNIQUEIDENTIFIER NULL,
    IdDiaDiem UNIQUEIDENTIFIER NOT NULL,
    HTGiangDay NVARCHAR(100) NOT NULL,
    TTDiemDanh BIT NOT NULL DEFAULT 0,
    NgayTao DATETIME NOT NULL DEFAULT GETDATE(),
    NgayCapNhat DATETIME NULL,
    TrangThai INT NOT NULL DEFAULT 1,

    CONSTRAINT FK_LGD_NXCH FOREIGN KEY (IdNXCH) REFERENCES CoSo(IdCoSo),
    CONSTRAINT FK_LGD_NhomXuong FOREIGN KEY (IdNhomXuong) REFERENCES NhomXuong(IdNhomXuong),
    CONSTRAINT FK_LGD_DuAn FOREIGN KEY (IdDuAn) REFERENCES DuAn(IdDuAn),
    CONSTRAINT FK_LGD_DiaDiem FOREIGN KEY (IdDiaDiem) REFERENCES DiaDiem(IdDiaDiem)
);

GO
CREATE TABLE KeHoach (
    IdKeHoach UNIQUEIDENTIFIER PRIMARY KEY,
    TenKeHoach NVARCHAR(255),
    IdDuAn UNIQUEIDENTIFIER,
    NoiDung NVARCHAR(MAX),
    NgayDienRa DATE,
    TrangThai INT,
    NgayTao DATETIME,
    NgayCapNhat DATETIME,

	CONSTRAINT FK_KeHoach_DuAn FOREIGN KEY (IdDuAn) REFERENCES DuAn(IdDuAn)
);
GO
CREATE TABLE KeHoachNhomXuong (
    IdKHNX UNIQUEIDENTIFIER PRIMARY KEY,
    IdNhomXuong UNIQUEIDENTIFIER,
    IdKeHoach UNIQUEIDENTIFIER,
    ThoiGianThucTe NVARCHAR(100),
    SoBuoi INT,
    SoSinhVien INT,
    NgayTao DATETIME,
    NgayCapNhat DATETIME,
    TrangThai INT,

	CONSTRAINT FK_KeHoachNhomXuong_NhomXuong FOREIGN KEY (IdNhomXuong) REFERENCES NhomXuong(IdNhomXuong),
    CONSTRAINT FK_KeHoachNhomXuong_KeHoach FOREIGN KEY (IdKeHoach) REFERENCES KeHoach(IdKeHoach)
);
go
CREATE TABLE KHNXCaHoc (
    IdNXCH UNIQUEIDENTIFIER PRIMARY KEY,
    Buoi INT,
    NgayHoc DATE,
    ThoiGian NVARCHAR(100),
    IdKHNX UNIQUEIDENTIFIER,
    IdCaHoc UNIQUEIDENTIFIER,
    NoiDung NVARCHAR(MAX),
    LinkOnline NVARCHAR(500),
    DiemDanhTre BIT,
    NgayTao DATETIME,
    NgayCapNhat DATETIME,
    TrangThai INT,

	CONSTRAINT FK_KHNXCaHoc_KHNhomXuong FOREIGN KEY (IdKHNX) REFERENCES NhomXuong(IdNhomXuong),
    CONSTRAINT FK_KHNXCaHoc_CaHoc FOREIGN KEY (IdCaHoc) REFERENCES CaHoc(IdCaHoc)
);

GO
CREATE TABLE VaiTroNhanVien (
    IdVaiTroNhanVien UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    IdVaiTro UNIQUEIDENTIFIER NULL,
    IdNhanVien UNIQUEIDENTIFIER NULL,
    NgayTao DATETIME NOT NULL DEFAULT GETDATE(),
    NgayCapNhat DATETIME NULL,
    TrangThai BIT NOT NULL DEFAULT 1,

    CONSTRAINT FK_VaiTroNhanVien_VaiTro FOREIGN KEY (IdVaiTro) REFERENCES VaiTro(IdVaiTro),
    CONSTRAINT FK_VaiTroNhanVien_NhanVien FOREIGN KEY (IdNhanVien) REFERENCES PhuTrachXuong(IdNhanVien)
);
GO
CREATE TABLE SinhVien (
    IdSinhVien UNIQUEIDENTIFIER PRIMARY KEY,
    TenSinhVien NVARCHAR(100),
    MaSinhVien NVARCHAR(50),
    Email NVARCHAR(100),
    IdNhomXuong UNIQUEIDENTIFIER, 
    TrangThai INT DEFAULT 1,
    NgayTao DATETIME,
    NgayCapNhat DATETIME,
    IdVaiTro UNIQUEIDENTIFIER,    

    CONSTRAINT FK_SinhVien_NhomXuong FOREIGN KEY (IdNhomXuong)
        REFERENCES NhomXuong(IdNhomXuong),

    CONSTRAINT FK_SinhVien_VaiTro FOREIGN KEY (IdVaiTro)
        REFERENCES VaiTro(IdVaiTro)
);
GO
CREATE TABLE DiemDanh (
    IdDiemDanh UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    IdSinhVien UNIQUEIDENTIFIER NOT NULL,
    IdCaHoc UNIQUEIDENTIFIER NOT NULL,
    IdNhomXuong UNIQUEIDENTIFIER NOT NULL,
    IdNhanVien UNIQUEIDENTIFIER NOT NULL,
    NgayTao DATETIME DEFAULT GETDATE(),

    CONSTRAINT FK_DiemDanh_SinhVien FOREIGN KEY (IdSinhVien) REFERENCES SinhVien(IdSinhVien),
    CONSTRAINT FK_DiemDanh_CaHoc FOREIGN KEY (IdCaHoc) REFERENCES CaHoc(IdCaHoc),
    CONSTRAINT FK_DiemDanh_NhomXuong FOREIGN KEY (IdNhomXuong) REFERENCES NhomXuong(IdNhomXuong),
    CONSTRAINT FK_DiemDanh_NhanVien FOREIGN KEY (IdNhanVien) REFERENCES PhuTrachXuong(IdNhanVien)
);
GO
CREATE TABLE LichSuDiemDanh (
    IdLSDD UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    IdDiemDanh UNIQUEIDENTIFIER NOT NULL,
    IdNXCH UNIQUEIDENTIFIER NOT NULL,
    ThoiGianDiemDanh DATETIME NOT NULL,
    NoiDungBuoiHoc NVARCHAR(255),
    HinhThuc NVARCHAR(100),
    DiaDiem NVARCHAR(100),
    GhiChu NVARCHAR(255),
    TrangThai INT NOT NULL DEFAULT 1,
    NgayTao DATETIME NOT NULL DEFAULT GETDATE(),
    NgayCapNhat DATETIME NULL,
    TrangThaiDuyet INT NOT NULL DEFAULT 1,

    CONSTRAINT FK_LSDD_DiemDanh FOREIGN KEY (IdDiemDanh) REFERENCES DiemDanh(IdDiemDanh),
    CONSTRAINT FK_LSDD_NXCH FOREIGN KEY (IdNXCH) REFERENCES CoSo(IdCoSo)
);

GO

